ver5: #测试自己生成的数据集V2
  #model settings
  model_conf:
    input_size: 6
    T: 20
    encoder_num_hidden: 32
    decoder_num_hidden: 32
    drop_ratio: 0
  
  #train settings
  train_conf:
    epoch: 1500
    batch: 256
    split: 30
    learning_rate: 0.001
    resume: True
    checkpoint_path: '../result/'
    log_file: 'trainer.log'

  #dataset settings
  data_conf:
    train_list: [2010,2011,2012,2013,2014,2015,2016,2017,2018]
    test_list: [123,456,789,1012]
    datapath: '../v2'

ver6: #刚重构后的版本
  #model settings
  model_conf:
    input_size: 6
    T: 20
    encoder_num_hidden: 32
    decoder_num_hidden: 32
    drop_ratio: 0
  
  #train settings
  train_conf:
    epoch: 1500
    batch: 256
    split: 30
    learning_rate: 0.001
    resume: True
    checkpoint_path: '../result/'
    log_file: 'trainer.log'

  #dataset settings
  data_conf:
    train_list: [2010,2011,2012,2013,2014,2015,2016,2017,2018]
    test_list: [123,456,789,1012]
    datapath: '../v1'
  
ver7: #darnn中替换成self-attention
  #model settings
  model_conf:
    input_size: 6
    T: 20
    encoder_num_hidden: 32
    decoder_num_hidden: 32
    drop_ratio: 0
  
  #train settings
  train_conf:
    epoch: 1500
    batch: 256
    split: 30
    learning_rate: 0.001
    resume: True
    checkpoint_path: '../result/'
    log_file: 'trainer.log'

  #dataset settings
  data_conf:
    train_list: [2010,2011,2012,2013,2014,2015,2016,2017,2018]
    test_list: [123,456,789,1012]
    datapath: '../v1'
